-- Generated by Matcha GUI Builder

local Mouse = game.Players.LocalPlayer:GetMouse()

print("=== PRESSURE SCRIPT - LOADING ===")

-- ========== SETTINGS ==========

local Settings = {
    notificationsEnabled = {
        Angler = false,
        Froger = false,
        Pinkie = false,
        Blitz = false,
        Pandemonium = false,
        Chainsmoker = false,
        ["A-60"] = false,
        Painter = false
    },
    keycardESPEnabled = false,
    doorESPEnabled = false,
    autoHideEnabled = false,
    watermarkEnabled = false,
    autoRescanEnabled = false,
    autoRescanInterval = 10,
    guiVisible = true
}

-- ========== NOTIFICATION SYSTEM ==========

local NotificationSystem = {
    activeNotifications = {},
    nextYPosition = 0,
    notificationHeight = 60,
    spacing = 10,
    maxNotifications = 5
}

local TrackedMobs = {"Angler", "Blitz", "Pinkie", "Pandemonium", "Froger", "Chainsmoker",
    "RidgeAngler", "RidgeBlitz", "RidgePinkie", "RidgePandemonium", "RidgeFroger", "RidgeChainsmoker", "A-60"}

local detectedMobs = {}

function NotificationSystem:CreateNotification(mobName, duration)
    if #self.activeNotifications >= self.maxNotifications then
        local oldest = table.remove(self.activeNotifications, 1)
        if oldest then
            pcall(function()
                oldest.background:Remove()
                oldest.border:Remove()
                oldest.text:Remove()
                oldest.progress:Remove()
            end)
            self.nextYPosition = self.nextYPosition - (self.notificationHeight + self.spacing)
        end
    end
    local camera = workspace.CurrentCamera
    local viewportSize = (camera and camera.ViewportSize) or Vector2.new(1920, 1080)
    local startX = viewportSize.X - 280
    local startY = viewportSize.Y - 80 - self.nextYPosition

    local background = Drawing.new("Square")
    background.Visible = true
    background.Transparency = 1
    background.ZIndex = 10
    background.Color = Color3.fromHex("#06070e")
    background.Position = Vector2.new(startX, startY)
    background.Size = Vector2.new(260, 60)
    background.Filled = true
    background.Corner = 8

    local border = Drawing.new("Square")
    border.Visible = true
    border.Transparency = 1
    border.ZIndex = 11
    border.Color = Color3.fromHex("#1c132f")
    border.Filled = false
    border.Thickness = 2
    border.Position = background.Position
    border.Size = background.Size
    border.Corner = 8

    local text = Drawing.new("Text")
    text.Visible = true
    text.Transparency = 0.75
    text.ZIndex = 20
    text.Color = Color3.fromHex("#FFFFFF")
    text.Position = Vector2.new(startX + 10, startY + 22)
    text.Text = mobName .. " spawned!"
    text.Size = 16
    text.Center = false
    text.Outline = true
    text.Font = Drawing.Fonts.UI

    local progress = Drawing.new("Square")
    progress.Visible = true
    progress.Transparency = 0.8
    progress.ZIndex = 12
    progress.Color = Color3.fromHex("#8a4dff")
    progress.Position = Vector2.new(startX, startY + 58)
    progress.Size = Vector2.new(260, 2)
    progress.Filled = true
    progress.Corner = 0

    local notification = {
        background = background,
        border = border,
        text = text,
        progress = progress,
        startTime = os.clock(),
        duration = duration or 5,
        targetY = startY
    }
    table.insert(self.activeNotifications, notification)
    self.nextYPosition = self.nextYPosition + (self.notificationHeight + self.spacing)
end

function NotificationSystem:Update()
    local currentTime = os.clock()
    local toRemove = {}
    for i, notif in ipairs(self.activeNotifications) do
        local elapsed = currentTime - notif.startTime
        local progress = math.min(elapsed / notif.duration, 1)
        local easedProgress = 1 - math.pow(1 - progress, 3)
        notif.progress.Size = Vector2.new(260 * (1 - easedProgress), 2)
        if elapsed >= notif.duration then
            local fadeProgress = math.min((elapsed - notif.duration) / 0.3, 1)
            local easedFade = math.pow(fadeProgress, 2)
            local alpha = 1 - easedFade
            notif.background.Transparency = alpha
            notif.border.Transparency = alpha
            notif.text.Transparency = 0.75 * alpha
            notif.progress.Transparency = 0.8 * alpha
            if fadeProgress >= 1 then
                table.insert(toRemove, i)
            end
        end
    end
    for i = #toRemove, 1, -1 do
        local idx = toRemove[i]
        local notif = table.remove(self.activeNotifications, idx)
        if notif then
            pcall(function()
                notif.background:Remove()
                notif.border:Remove()
                notif.text:Remove()
                notif.progress:Remove()
            end)
        end
    end
    if #toRemove > 0 then
        self.nextYPosition = 0
        for i, notif in ipairs(self.activeNotifications) do
            local camera = workspace.CurrentCamera
            local viewportSize = (camera and camera.ViewportSize) or Vector2.new(1920, 1080)
            local targetY = viewportSize.Y - 80 - self.nextYPosition
            local currentY = notif.background.Position.Y
            local newY = currentY + (targetY - currentY) * 0.15
            notif.background.Position = Vector2.new(notif.background.Position.X, newY)
            notif.border.Position = Vector2.new(notif.border.Position.X, newY)
            notif.text.Position = Vector2.new(notif.text.Position.X, newY + 22)
            notif.progress.Position = Vector2.new(notif.progress.Position.X, newY + 58)
            self.nextYPosition = self.nextYPosition + (self.notificationHeight + self.spacing)
        end
    end
end

function NotificationSystem:CheckForMobs()
    local currentFrameMobs = {}
    for _, obj in ipairs(workspace:GetChildren()) do
        local mobName = obj.Name
        for _, targetMob in ipairs(TrackedMobs) do
            if mobName == targetMob then
                currentFrameMobs[mobName] = true
                if not detectedMobs[mobName] then
                    detectedMobs[mobName] = true
                    local simpleName = mobName:gsub("Ridge", "")
                    if Settings.notificationsEnabled[simpleName] then
                        self:CreateNotification(mobName, 5)
                        print("Notification: " .. mobName .. " spawned!")
                    end
                    if WatermarkSystem then
                        WatermarkSystem.currentEntity = mobName
                    end
                end
                break
            end
        end
    end
    for mobName, _ in pairs(detectedMobs) do
        if not currentFrameMobs[mobName] then
            detectedMobs[mobName] = nil
        end
    end
end

-- ========== WATERMARK SYSTEM ==========

WatermarkSystem = {
    enabled = false,
    currentEntity = "NoEntities",
    elements = {}
}

local MobColors = {
    Angler = Color3.fromHex("#00ff00"),
    Blitz = Color3.fromHex("#ff0000"),
    Pinkie = Color3.fromHex("#ff66cc"),
    Pandemonium = Color3.fromHex("#8000ff"),
    Froger = Color3.fromHex("#00ffff"),
    Chainsmoker = Color3.fromHex("#808080"),
    ["A-60"] = Color3.fromHex("#ffff00")
}

local function getCenterPosition()
    local camera = workspace.CurrentCamera
    local viewportSize = camera.ViewportSize
    local centerX = (viewportSize.X / 2) - (307 / 2)
    return Vector2.new(centerX, 60)
end

function WatermarkSystem:Initialize()
    local pos = getCenterPosition()
    self.elements.background = Drawing.new("Square")
    self.elements.background.Visible = false
    self.elements.background.Transparency = 1
    self.elements.background.ZIndex = 10
    self.elements.background.Color = Color3.fromHex("#0a0e1e")
    self.elements.background.Position = pos
    self.elements.background.Size = Vector2.new(307, 32)
    self.elements.background.Filled = true
    self.elements.background.Corner = 15

    self.elements.border = Drawing.new("Square")
    self.elements.border.Visible = false
    self.elements.border.Transparency = 1
    self.elements.border.ZIndex = 11
    self.elements.border.Color = Color3.fromHex("#000000")
    self.elements.border.Filled = false
    self.elements.border.Thickness = 2
    self.elements.border.Position = pos
    self.elements.border.Size = Vector2.new(307, 32)
    self.elements.border.Corner = 15

    self.elements.pressure = Drawing.new("Text")
    self.elements.pressure.Visible = false
    self.elements.pressure.Transparency = 1
    self.elements.pressure.ZIndex = 20
    self.elements.pressure.Color = Color3.fromHex("#cd0e0e")
    self.elements.pressure.Position = pos + Vector2.new(26.5, 11)
    self.elements.pressure.Text = "Pressure"
    self.elements.pressure.Size = 12
    self.elements.pressure.Center = false
    self.elements.pressure.Outline = true
    self.elements.pressure.Font = Drawing.Fonts.UI

    self.elements.circle1 = Drawing.new("Circle")
    self.elements.circle1.Visible = false
    self.elements.circle1.Transparency = 1
    self.elements.circle1.ZIndex = 30
    self.elements.circle1.Color = Color3.fromHex("#ca0707")
    self.elements.circle1.Position = pos + Vector2.new(95, 16)
    self.elements.circle1.Radius = 4
    self.elements.circle1.NumSides = 32
    self.elements.circle1.Thickness = 1
    self.elements.circle1.Filled = true

    self.elements.circle2 = Drawing.new("Circle")
    self.elements.circle2.Visible = false
    self.elements.circle2.Transparency = 1
    self.elements.circle2.ZIndex = 30
    self.elements.circle2.Color = Color3.fromHex("#ca0707")
    self.elements.circle2.Position = pos + Vector2.new(120, 16)
    self.elements.circle2.Radius = 4
    self.elements.circle2.NumSides = 32
    self.elements.circle2.Thickness = 1
    self.elements.circle2.Filled = true

    self.elements.circle3 = Drawing.new("Circle")
    self.elements.circle3.Visible = false
    self.elements.circle3.Transparency = 1
    self.elements.circle3.ZIndex = 30
    self.elements.circle3.Color = Color3.fromHex("#ca0707")
    self.elements.circle3.Position = pos + Vector2.new(143.5, 16)
    self.elements.circle3.Radius = 4
    self.elements.circle3.NumSides = 32
    self.elements.circle3.Thickness = 1
    self.elements.circle3.Filled = true

    self.elements.status = Drawing.new("Text")
    self.elements.status.Visible = false
    self.elements.status.Transparency = 1
    self.elements.status.ZIndex = 60
    self.elements.status.Color = Color3.fromHex("#b0b0b0")
    self.elements.status.Position = pos + Vector2.new(171.5, 11)
    self.elements.status.Text = "STATUS"
    self.elements.status.Size = 12
    self.elements.status.Center = false
    self.elements.status.Outline = true
    self.elements.status.Font = Drawing.Fonts.UI

    self.elements.entity = Drawing.new("Text")
    self.elements.entity.Visible = false
    self.elements.entity.Transparency = 1
    self.elements.entity.ZIndex = 70
    self.elements.entity.Color = Color3.fromHex("#1cf000")
    self.elements.entity.Position = pos + Vector2.new(226.5, 11)
    self.elements.entity.Text = "NoEntities"
    self.elements.entity.Size = 12
    self.elements.entity.Center = false
    self.elements.entity.Outline = true
    self.elements.entity.Font = Drawing.Fonts.UI
end

function WatermarkSystem:SetVisible(visible)
    for _, element in pairs(self.elements) do
        if element and element.Visible ~= nil then
            element.Visible = visible and self.enabled
        end
    end
end

function WatermarkSystem:CheckForMobs()
    for _, obj in ipairs(workspace:GetChildren()) do
        for _, targetMob in ipairs(TrackedMobs) do
            if obj.Name == targetMob then
                return targetMob
            end
        end
    end
    return nil
end

function WatermarkSystem:UpdateEntity()
    if not self.elements.entity then return end
    local mob = self:CheckForMobs()
    if mob then
        self.currentEntity = mob
        self.elements.entity.Text = mob
        self.elements.entity.Color = MobColors[mob] or Color3.fromHex("#ff0000")
    else
        self.currentEntity = "NoEntities"
        self.elements.entity.Text = "NoEntities"
        self.elements.entity.Color = Color3.fromHex("#1cf000")
    end
end

local watermarkDragging = nil
local watermarkDragStart = nil
local watermarkStartPos = nil
local lastWatermarkMouse1 = false

spawn(function()
    while true do
        wait(0.01)
        if isrbxactive() and WatermarkSystem.elements.background then
            local mouse1 = ismouse1pressed()
            local mPos = Vector2.new(Mouse.X, Mouse.Y)
            local bg = WatermarkSystem.elements.background
            if mouse1 and not lastWatermarkMouse1 then
                if bg.Visible and mPos.X >= bg.Position.X and mPos.X <= bg.Position.X + bg.Size.X
                    and mPos.Y >= bg.Position.Y and mPos.Y <= bg.Position.Y + bg.Size.Y then
                    watermarkDragging = bg
                    watermarkDragStart = mPos
                    watermarkStartPos = bg.Position
                end
            end
            if not mouse1 and lastWatermarkMouse1 then
                watermarkDragging = nil
            end
            if watermarkDragging and mouse1 then
                local delta = mPos - watermarkDragStart
                local newPos = watermarkStartPos + delta
                WatermarkSystem.elements.background.Position = newPos
                WatermarkSystem.elements.border.Position = newPos
                WatermarkSystem.elements.pressure.Position = newPos + Vector2.new(26.5, 11)
                WatermarkSystem.elements.circle1.Position = newPos + Vector2.new(95, 16)
                WatermarkSystem.elements.circle2.Position = newPos + Vector2.new(120, 16)
                WatermarkSystem.elements.circle3.Position = newPos + Vector2.new(143.5, 16)
                WatermarkSystem.elements.status.Position = newPos + Vector2.new(171.5, 11)
                WatermarkSystem.elements.entity.Position = newPos + Vector2.new(226.5, 11)
            end
            lastWatermarkMouse1 = mouse1
        end
    end
end)

-- ========== ESP SYSTEM ==========

loadstring(game:HttpGet("https://www.arcanecheats.xyz/api/matcha/esplib"))()

local activeESPs = {}

local KeycardConfigs = {
    KeyCard = {color = Color3.fromRGB(0, 255, 0), name = "KeyCard"},
    RidgeKeyCard = {color = Color3.fromRGB(255, 255, 0), name = "RidgeKey"},
    PasswordPaper = {color = Color3.fromRGB(0, 150, 255), name = "Password"},
    InnerKeyCard = {color = Color3.fromRGB(138, 43, 226), name = "InnerKey"}
}

local function FindKeycards()
    local foundItems = {}
    local gameplayFolder = workspace:FindFirstChild("GameplayFolder")
    if not gameplayFolder then return foundItems end
    local rooms = gameplayFolder:FindFirstChild("Rooms")
    if not rooms then return foundItems end
    for _, obj in ipairs(rooms:GetDescendants()) do
        local interactionType = obj:GetAttribute("InteractionType")
        if KeycardConfigs[interactionType] then
            table.insert(foundItems, {
                model = obj,
                type = interactionType,
                config = KeycardConfigs[interactionType]
            })
        end
    end
    return foundItems
end

local function CreateESP(item)
    local key = item.model:GetFullName()
    local config = item.config
    local success, esp = pcall(function()
        return ArcaneEsp.new(item.model)
            :AddEsp(config.color)
            :AddTitle(Color3.new(1, 1, 1), config.name)
            :AddDistance(Color3.new(1, 1, 1))
            :SetFont(0)
    end)
    if not success or not esp then return nil end
    return {esp = esp, model = item.model, key = key}
end

local function StartKeycardESP()
    if Settings.keycardESPEnabled then return end
    Settings.keycardESPEnabled = true
    local items = FindKeycards()
    for _, item in ipairs(items) do
        local espData = CreateESP(item)
        if espData then
            activeESPs[espData.key] = espData
        end
    end
    print("ESP Activated: " .. #items .. " items")
end

local function CleanupKeycardESP()
    Settings.keycardESPEnabled = false
    for key, espData in pairs(activeESPs) do
        pcall(function() espData.esp:Destroy() end)
    end
    activeESPs = {}
    print("ESP Cleaned up")
end

local lastRescanTime = 0

local function ForceRescanESP()
    if not Settings.keycardESPEnabled then return end
    pcall(function()
        local newItems = FindKeycards()
        local newKeys = {}
        for _, item in ipairs(newItems) do
            newKeys[item.model:GetFullName()] = item
        end
        for key, espData in pairs(activeESPs) do
            if not newKeys[key] then
                pcall(function() espData.esp:Destroy() end)
                activeESPs[key] = nil
            end
        end
        for key, item in pairs(newKeys) do
            if not activeESPs[key] then
                local espData = CreateESP(item)
                if espData then
                    activeESPs[espData.key] = espData
                end
            end
        end
        print("ESP Rescanned: " .. #newItems .. " items found")
    end)
end

spawn(function()
    while true do
        wait(1)
        if Settings.autoRescanEnabled and Settings.keycardESPEnabled then
            local currentTime = os.clock()
            if currentTime - lastRescanTime >= Settings.autoRescanInterval then
                lastRescanTime = currentTime
                ForceRescanESP()
            end
        end
    end
end)

-- ========== DOOR ESP SYSTEM ==========

local activeDoorESPs = {}

local function FindDoors()
    local foundDoors = {}
    local gf = workspace:FindFirstChild("GameplayFolder")
    if not gf then return foundDoors end
    local rooms = gf:FindFirstChild("Rooms")
    if not rooms then return foundDoors end
    for _, room in ipairs(rooms:GetChildren()) do
        local exits = room:FindFirstChild("Exits")
        if exits then
            for _, exitObj in ipairs(exits:GetChildren()) do
                local part = nil
                if exitObj:IsA("BasePart") then
                    part = exitObj
                else
                    part = exitObj:FindFirstChildWhichIsA("BasePart", true)
                end
                if part then
                    table.insert(foundDoors, {part = part, key = exitObj:GetFullName()})
                end
            end
        end
    end
    return foundDoors
end

local function StartDoorESP()
    if Settings.doorESPEnabled then return end
    Settings.doorESPEnabled = true
    local doors = FindDoors()
    for _, door in ipairs(doors) do
        if not activeDoorESPs[door.key] then
            local ok, esp = pcall(function()
                return ArcaneEsp.new(door.part)
                    :AddEsp(Color3.fromRGB(255, 165, 0))
                    :AddTitle(Color3.new(1,1,1), "Door")
                    :AddDistance(Color3.new(1,1,1))
                    :SetFont(0)
            end)
            if ok and esp then activeDoorESPs[door.key] = esp end
        end
    end
    print("Door ESP ON: " .. #doors .. " doors")
end

local function CleanupDoorESP()
    Settings.doorESPEnabled = false
    for key, esp in pairs(activeDoorESPs) do
        pcall(function() esp:Destroy() end)
        activeDoorESPs[key] = nil
    end
    print("Door ESP OFF")
end

spawn(function()
    while true do
        wait(3)
        if Settings.doorESPEnabled then
            local doors = FindDoors()
            local newKeys = {}
            for _, d in ipairs(doors) do newKeys[d.key] = d end
            for key, esp in pairs(activeDoorESPs) do
                if not newKeys[key] then
                    pcall(function() esp:Destroy() end)
                    activeDoorESPs[key] = nil
                end
            end
            for key, d in pairs(newKeys) do
                if not activeDoorESPs[key] then
                    local ok, esp = pcall(function()
                        return ArcaneEsp.new(d.part)
                            :AddEsp(Color3.fromRGB(255, 165, 0))
                            :AddTitle(Color3.new(1,1,1), "Door")
                            :AddDistance(Color3.new(1,1,1))
                            :SetFont(0)
                    end)
                    if ok and esp then activeDoorESPs[key] = esp end
                end
            end
        end
    end
end)

-- ========== AUTOHIDE SYSTEM ==========

local Players = game.Players

local AutoHideSystem = {
    enabled = false,
    isHiding = false,
    originalPosition = nil,
    checkInterval = 0.05,
    lastCheckTime = 0,
    holdLoop = false
}

local function getHRP()
    local player = Players.LocalPlayer
    if not player or not player.Character then return nil end
    return player.Character:FindFirstChild("HumanoidRootPart")
end

function AutoHideSystem:CheckForMobs()
    local foundMobs = {}
    for _, obj in ipairs(workspace:GetChildren()) do
        for _, targetMob in ipairs(TrackedMobs) do
            if obj.Name == targetMob then
                table.insert(foundMobs, targetMob)
                break
            end
        end
    end
    return foundMobs
end

function AutoHideSystem:Hide()
    if self.isHiding then return end
    local success, err = pcall(function()
        local hrp = getHRP()
        if not hrp then return end
        print("AutoHide: Hiding player...")
        self.originalPosition = hrp.Position
        self.isHiding = true
        local newPos = self.originalPosition + Vector3.new(0, 1000, 0)
        hrp.Position = newPos
        hrp.Velocity = Vector3.new(0, 0, 0)
        hrp.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
        self.holdLoop = true
        spawn(function()
            while self.holdLoop do
                local currentHrp = getHRP()
                if currentHrp then
                    currentHrp.Velocity = Vector3.new(0, 0, 0)
                    currentHrp.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
                end
                wait(0.01)
            end
        end)
    end)
    if not success then
        print("AutoHide Error: " .. tostring(err))
        self.isHiding = false
    end
end

function AutoHideSystem:Unhide()
    if not self.isHiding then return end
    pcall(function()
        local hrp = getHRP()
        if not hrp then return end
        print("AutoHide: Unhiding player...")
        self.holdLoop = false
        if self.originalPosition then
            hrp.Position = self.originalPosition
            hrp.Velocity = Vector3.new(0, 0, 0)
            hrp.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
        end
        self.isHiding = false
        self.originalPosition = nil
    end)
end

function AutoHideSystem:Update()
    if not self.enabled then
        if self.isHiding then self:Unhide() end
        return
    end
    local currentTime = os.clock()
    if currentTime - self.lastCheckTime < self.checkInterval then return end
    self.lastCheckTime = currentTime
    local foundMobs = self:CheckForMobs()
    if #foundMobs > 0 then
        if not self.isHiding then self:Hide() end
    else
        if self.isHiding then self:Unhide() end
    end
end

-- ========== UPDATE LOOPS ==========

spawn(function()
    while true do
        pcall(function() NotificationSystem:Update() end)
        wait(0.016)
    end
end)

spawn(function()
    while true do
        pcall(function() NotificationSystem:CheckForMobs() end)
        wait(0.1)
    end
end)

spawn(function()
    while true do
        if WatermarkSystem.enabled then
            pcall(function() WatermarkSystem:UpdateEntity() end)
        end
        wait(0.1)
    end
end)

spawn(function()
    while true do
        pcall(function() AutoHideSystem:Update() end)
        wait(0.01)
    end
end)

WatermarkSystem:Initialize()
print("=== SYSTEMS LOADED ===")

-- ========== GUI CODE START ==========

local MainUIsystem = Drawing.new("Square")
MainUIsystem.Visible = true
MainUIsystem.Transparency = 1
MainUIsystem.ZIndex = 10
MainUIsystem.Color = Color3.fromHex("#0a0b10")
MainUIsystem.Position = Vector2.new(39.5, 70)
MainUIsystem.Size = Vector2.new(721, 431)
MainUIsystem.Filled = true
MainUIsystem.Corner = 7

local MainUIsystemBorder = Drawing.new("Square")
MainUIsystemBorder.Visible = true
MainUIsystemBorder.Transparency = 1
MainUIsystemBorder.ZIndex = 11
MainUIsystemBorder.Color = Color3.fromHex("#100b1e")
MainUIsystemBorder.Filled = false
MainUIsystemBorder.Thickness = 3
MainUIsystemBorder.Position = MainUIsystem.Position
MainUIsystemBorder.Size = MainUIsystem.Size
MainUIsystemBorder.Corner = 7

local Line = Drawing.new("Square")
Line.Visible = true
Line.Transparency = 1
Line.ZIndex = 20
Line.Color = Color3.fromHex("#0a0f1f")
Line.Position = MainUIsystem.Position + Vector2.new(188.5, 0)
Line.Size = Vector2.new(2, 430)
Line.Filled = true
Line.Corner = 10

local LineBorder = Drawing.new("Square")
LineBorder.Visible = true
LineBorder.Transparency = 1
LineBorder.ZIndex = 21
LineBorder.Color = Color3.fromHex("#0a0f1f")
LineBorder.Filled = false
LineBorder.Thickness = 1
LineBorder.Position = Line.Position
LineBorder.Size = Line.Size
LineBorder.Corner = 10

local Line1 = Drawing.new("Square")
Line1.Visible = true
Line1.Transparency = 1
Line1.ZIndex = 30
Line1.Color = Color3.fromHex("#0a0f1f")
Line1.Position = MainUIsystem.Position + Vector2.new(0, 43)
Line1.Size = Vector2.new(191, 2)
Line1.Filled = true
Line1.Corner = 10

local Line1Border = Drawing.new("Square")
Line1Border.Visible = true
Line1Border.Transparency = 1
Line1Border.ZIndex = 31
Line1Border.Color = Color3.fromHex("#0a0f1f")
Line1Border.Filled = false
Line1Border.Thickness = 1
Line1Border.Position = Line1.Position
Line1Border.Size = Line1.Size
Line1Border.Corner = 10

local RATHUBlogo = Drawing.new("Text")
RATHUBlogo.Visible = true
RATHUBlogo.Transparency = 1
RATHUBlogo.ZIndex = 50
RATHUBlogo.Color = Color3.fromHex("#FFFFFF")
RATHUBlogo.Position = MainUIsystem.Position + Vector2.new(71.5, 15)
RATHUBlogo.Text = "Rathub"
RATHUBlogo.Size = 17
RATHUBlogo.Center = false
RATHUBlogo.Outline = false
RATHUBlogo.Font = Drawing.Fonts.UI

local Line2 = Drawing.new("Square")
Line2.Visible = true
Line2.Transparency = 1
Line2.ZIndex = 40
Line2.Color = Color3.fromHex("#0a0f1f")
Line2.Position = MainUIsystem.Position + Vector2.new(191.5, 43)
Line2.Size = Vector2.new(528, 2)
Line2.Filled = true
Line2.Corner = 10

local Line2Border = Drawing.new("Square")
Line2Border.Visible = true
Line2Border.Transparency = 1
Line2Border.ZIndex = 41
Line2Border.Color = Color3.fromHex("#0a0f1f")
Line2Border.Filled = false
Line2Border.Thickness = 1
Line2Border.Position = Line2.Position
Line2Border.Size = Line2.Size
Line2Border.Corner = 10

local HOMEtabB = Drawing.new("Square")
HOMEtabB.Visible = true
HOMEtabB.Transparency = 1
HOMEtabB.ZIndex = 60
HOMEtabB.Color = Color3.fromHex("#0e0e16")
HOMEtabB.Position = MainUIsystem.Position + Vector2.new(9.5, 51)
HOMEtabB.Size = Vector2.new(172, 43)
HOMEtabB.Filled = true
HOMEtabB.Corner = 7

local HOMEtabBText = Drawing.new("Text")
HOMEtabBText.Text = "Home"
HOMEtabBText.Size = 14
HOMEtabBText.Center = true
HOMEtabBText.Outline = false
HOMEtabBText.Font = 0
HOMEtabBText.Color = Color3.fromHex("#bfbfbf")
HOMEtabBText.Position = HOMEtabB.Position + Vector2.new(172/2, 43/2)
HOMEtabBText.Visible = true
HOMEtabBText.ZIndex = 62

local TabVisualsB = Drawing.new("Square")
TabVisualsB.Visible = true
TabVisualsB.Transparency = 1
TabVisualsB.ZIndex = 70
TabVisualsB.Color = Color3.fromHex("#0e0e16")
TabVisualsB.Position = MainUIsystem.Position + Vector2.new(9.5, 103)
TabVisualsB.Size = Vector2.new(172, 43)
TabVisualsB.Filled = true
TabVisualsB.Corner = 7

local TabVisualsBText = Drawing.new("Text")
TabVisualsBText.Text = "Visuals"
TabVisualsBText.Size = 14
TabVisualsBText.Center = true
TabVisualsBText.Outline = false
TabVisualsBText.Font = 0
TabVisualsBText.Color = Color3.fromHex("#bfbfbf")
TabVisualsBText.Position = TabVisualsB.Position + Vector2.new(172/2, 43/2)
TabVisualsBText.Visible = true
TabVisualsBText.ZIndex = 72

local MiscTAB = Drawing.new("Square")
MiscTAB.Visible = true
MiscTAB.Transparency = 1
MiscTAB.ZIndex = 70
MiscTAB.Color = Color3.fromHex("#0e0e16")
MiscTAB.Position = MainUIsystem.Position + Vector2.new(9.5, 154)
MiscTAB.Size = Vector2.new(172, 43)
MiscTAB.Filled = true
MiscTAB.Corner = 7

local MiscTABText = Drawing.new("Text")
MiscTABText.Text = "Misc"
MiscTABText.Size = 14
MiscTABText.Center = true
MiscTABText.Outline = false
MiscTABText.Font = 0
MiscTABText.Color = Color3.fromHex("#bfbfbf")
MiscTABText.Position = MiscTAB.Position + Vector2.new(172/2, 43/2)
MiscTABText.Visible = true
MiscTABText.ZIndex = 72

local SettingsTAB = Drawing.new("Square")
SettingsTAB.Visible = true
SettingsTAB.Transparency = 1
SettingsTAB.ZIndex = 70
SettingsTAB.Color = Color3.fromHex("#0e0e16")
SettingsTAB.Position = MainUIsystem.Position + Vector2.new(9.5, 369)
SettingsTAB.Size = Vector2.new(172, 43)
SettingsTAB.Filled = true
SettingsTAB.Corner = 7

local SettingsTABText = Drawing.new("Text")
SettingsTABText.Text = "Settings"
SettingsTABText.Size = 14
SettingsTABText.Center = true
SettingsTABText.Outline = false
SettingsTABText.Font = 0
SettingsTABText.Color = Color3.fromHex("#bfbfbf")
SettingsTABText.Position = SettingsTAB.Position + Vector2.new(172/2, 43/2)
SettingsTABText.Visible = true
SettingsTABText.ZIndex = 72

-- Tab Containers
local TabHomeContainer1 = Drawing.new("Square")
TabHomeContainer1.Visible = false
TabHomeContainer1.Transparency = 1
TabHomeContainer1.ZIndex = 80
TabHomeContainer1.Color = Color3.fromHex("#0e0e16")
TabHomeContainer1.Position = MainUIsystem.Position + Vector2.new(476.5, 57.5)
TabHomeContainer1.Size = Vector2.new(225, 345)
TabHomeContainer1.Filled = true
TabHomeContainer1.Corner = 7

local WorkGames1 = Drawing.new("Circle")
WorkGames1.Visible = false
WorkGames1.Transparency = 1
WorkGames1.ZIndex = 90
WorkGames1.Color = Color3.fromHex("#0fff13")
WorkGames1.Position = TabHomeContainer1.Position + Vector2.new(21, 23.5)
WorkGames1.Radius = 7
WorkGames1.NumSides = 32
WorkGames1.Thickness = 1
WorkGames1.Filled = true

local PressureWORK = Drawing.new("Text")
PressureWORK.Visible = false
PressureWORK.Transparency = 1
PressureWORK.ZIndex = 100
PressureWORK.Color = Color3.fromHex("#bababa")
PressureWORK.Position = TabHomeContainer1.Position + Vector2.new(39, 14.5)
PressureWORK.Text = "Pressure"
PressureWORK.Size = 14
PressureWORK.Center = false
PressureWORK.Outline = true
PressureWORK.Font = Drawing.Fonts.UI

local TabVisualsContainer = Drawing.new("Square")
TabVisualsContainer.Visible = false
TabVisualsContainer.Transparency = 1
TabVisualsContainer.ZIndex = 110
TabVisualsContainer.Color = Color3.fromHex("#0e0e16")
TabVisualsContainer.Position = MainUIsystem.Position + Vector2.new(207.5, 58)
TabVisualsContainer.Size = Vector2.new(472, 332)
TabVisualsContainer.Filled = true
TabVisualsContainer.Corner = 7

-- Switch Angler
local AnglerIsChecked = false
local Angler = Drawing.new("Square")
Angler.Visible = false
Angler.Transparency = 1
Angler.Color = Color3.fromHex("#000000")
Angler.Thickness = 1
Angler.Filled = false
Angler.Size = Vector2.new(40, 20)
Angler.Position = Vector2.new(278, 209)
Angler.ZIndex = 130
Angler.Corner = 7

local AnglerBg = Drawing.new("Square")
AnglerBg.Visible = false
AnglerBg.Transparency = 1
AnglerBg.Color = Color3.fromHex("#1b1b2c")
AnglerBg.Filled = true
AnglerBg.Size = Angler.Size
AnglerBg.Position = Angler.Position
AnglerBg.ZIndex = 130
AnglerBg.Corner = 7

local AnglerIndBorder = Drawing.new("Square")
AnglerIndBorder.Visible = false
AnglerIndBorder.Transparency = 1
AnglerIndBorder.Color = Color3.fromHex("#000000")
AnglerIndBorder.Thickness = 1
AnglerIndBorder.Filled = false
AnglerIndBorder.Size = Vector2.new(18, 18)
AnglerIndBorder.ZIndex = 132
AnglerIndBorder.Corner = 7

local AnglerInd = Drawing.new("Square")
AnglerInd.Visible = false
AnglerInd.Transparency = 1
AnglerInd.Color = Color3.fromHex("#20b120")
AnglerInd.Filled = true
AnglerInd.Size = Vector2.new(18, 18)
AnglerInd.ZIndex = 132
AnglerInd.Corner = 7

AnglerIndBorder.Position = Angler.Position + Vector2.new(1, 1)
AnglerInd.Position = Angler.Position + Vector2.new(1, 1)

local AnglerLabel = Drawing.new("Text")
AnglerLabel.Visible = false
AnglerLabel.Text = "Angler"
AnglerLabel.Size = 12
AnglerLabel.Color = Color3.fromHex("#a1a1a1")
AnglerLabel.Outline = true
AnglerLabel.Font = Drawing.Fonts.UI
AnglerLabel.Position = Angler.Position + Vector2.new(50, 4)
AnglerLabel.ZIndex = 131

-- Switch Froger
local FrogerIsChecked = false
local Froger = Drawing.new("Square")
Froger.Visible = false
Froger.Transparency = 1
Froger.Color = Color3.fromHex("#000000")
Froger.Thickness = 1
Froger.Filled = false
Froger.Size = Vector2.new(40, 20)
Froger.Position = Vector2.new(278, 238)
Froger.ZIndex = 140
Froger.Corner = 7

local FrogerBg = Drawing.new("Square")
FrogerBg.Visible = false
FrogerBg.Transparency = 1
FrogerBg.Color = Color3.fromHex("#1b1b2c")
FrogerBg.Filled = true
FrogerBg.Size = Froger.Size
FrogerBg.Position = Froger.Position
FrogerBg.ZIndex = 140
FrogerBg.Corner = 7

local FrogerIndBorder = Drawing.new("Square")
FrogerIndBorder.Visible = false
FrogerIndBorder.Transparency = 1
FrogerIndBorder.Color = Color3.fromHex("#000000")
FrogerIndBorder.Thickness = 1
FrogerIndBorder.Filled = false
FrogerIndBorder.Size = Vector2.new(18, 18)
FrogerIndBorder.ZIndex = 142
FrogerIndBorder.Corner = 7

local FrogerInd = Drawing.new("Square")
FrogerInd.Visible = false
FrogerInd.Transparency = 1
FrogerInd.Color = Color3.fromHex("#20b120")
FrogerInd.Filled = true
FrogerInd.Size = Vector2.new(18, 18)
FrogerInd.ZIndex = 142
FrogerInd.Corner = 7

FrogerIndBorder.Position = Froger.Position + Vector2.new(1, 1)
FrogerInd.Position = Froger.Position + Vector2.new(1, 1)

local FrogerLabel = Drawing.new("Text")
FrogerLabel.Visible = false
FrogerLabel.Text = "Froger"
FrogerLabel.Size = 12
FrogerLabel.Color = Color3.fromHex("#a1a1a1")
FrogerLabel.Outline = true
FrogerLabel.Font = Drawing.Fonts.UI
FrogerLabel.Position = Froger.Position + Vector2.new(50, 4)
FrogerLabel.ZIndex = 141

-- Switch Pinkie
local PinkieIsChecked = false
local Pinkie = Drawing.new("Square")
Pinkie.Visible = false
Pinkie.Transparency = 1
Pinkie.Color = Color3.fromHex("#000000")
Pinkie.Thickness = 1
Pinkie.Filled = false
Pinkie.Size = Vector2.new(40, 20)
Pinkie.Position = Vector2.new(278, 268)
Pinkie.ZIndex = 150
Pinkie.Corner = 7

local PinkieBg = Drawing.new("Square")
PinkieBg.Visible = false
PinkieBg.Transparency = 1
PinkieBg.Color = Color3.fromHex("#1b1b2c")
PinkieBg.Filled = true
PinkieBg.Size = Pinkie.Size
PinkieBg.Position = Pinkie.Position
PinkieBg.ZIndex = 150
PinkieBg.Corner = 7

local PinkieIndBorder = Drawing.new("Square")
PinkieIndBorder.Visible = false
PinkieIndBorder.Transparency = 1
PinkieIndBorder.Color = Color3.fromHex("#000000")
PinkieIndBorder.Thickness = 1
PinkieIndBorder.Filled = false
PinkieIndBorder.Size = Vector2.new(18, 18)
PinkieIndBorder.ZIndex = 152
PinkieIndBorder.Corner = 7

local PinkieInd = Drawing.new("Square")
PinkieInd.Visible = false
PinkieInd.Transparency = 1
PinkieInd.Color = Color3.fromHex("#20b120")
PinkieInd.Filled = true
PinkieInd.Size = Vector2.new(18, 18)
PinkieInd.ZIndex = 152
PinkieInd.Corner = 7

PinkieIndBorder.Position = Pinkie.Position + Vector2.new(1, 1)
PinkieInd.Position = Pinkie.Position + Vector2.new(1, 1)

local PinkieLabel = Drawing.new("Text")
PinkieLabel.Visible = false
PinkieLabel.Text = "Pinkie"
PinkieLabel.Size = 12
PinkieLabel.Color = Color3.fromHex("#a1a1a1")
PinkieLabel.Outline = true
PinkieLabel.Font = Drawing.Fonts.UI
PinkieLabel.Position = Pinkie.Position + Vector2.new(50, 4)
PinkieLabel.ZIndex = 151

-- Switch Blitz
local BlitzIsChecked = false
local Blitz = Drawing.new("Square")
Blitz.Visible = false
Blitz.Transparency = 1
Blitz.Color = Color3.fromHex("#000000")
Blitz.Thickness = 1
Blitz.Filled = false
Blitz.Size = Vector2.new(40, 20)
Blitz.Position = Vector2.new(278, 298)
Blitz.ZIndex = 160
Blitz.Corner = 7

local BlitzBg = Drawing.new("Square")
BlitzBg.Visible = false
BlitzBg.Transparency = 1
BlitzBg.Color = Color3.fromHex("#1b1b2c")
BlitzBg.Filled = true
BlitzBg.Size = Blitz.Size
BlitzBg.Position = Blitz.Position
BlitzBg.ZIndex = 160
BlitzBg.Corner = 7

local BlitzIndBorder = Drawing.new("Square")
BlitzIndBorder.Visible = false
BlitzIndBorder.Transparency = 1
BlitzIndBorder.Color = Color3.fromHex("#000000")
BlitzIndBorder.Thickness = 1
BlitzIndBorder.Filled = false
BlitzIndBorder.Size = Vector2.new(18, 18)
BlitzIndBorder.ZIndex = 162
BlitzIndBorder.Corner = 7

local BlitzInd = Drawing.new("Square")
BlitzInd.Visible = false
BlitzInd.Transparency = 1
BlitzInd.Color = Color3.fromHex("#20b120")
BlitzInd.Filled = true
BlitzInd.Size = Vector2.new(18, 18)
BlitzInd.ZIndex = 162
BlitzInd.Corner = 7

BlitzIndBorder.Position = Blitz.Position + Vector2.new(1, 1)
BlitzInd.Position = Blitz.Position + Vector2.new(1, 1)

local BlitzLabel = Drawing.new("Text")
BlitzLabel.Visible = false
BlitzLabel.Text = "Blitz"
BlitzLabel.Size = 12
BlitzLabel.Color = Color3.fromHex("#a1a1a1")
BlitzLabel.Outline = true
BlitzLabel.Font = Drawing.Fonts.UI
BlitzLabel.Position = Blitz.Position + Vector2.new(50, 4)
BlitzLabel.ZIndex = 161

-- Switch Pandemonium
local PandemoniumIsChecked = false
local Pandemonium = Drawing.new("Square")
Pandemonium.Visible = false
Pandemonium.Transparency = 1
Pandemonium.Color = Color3.fromHex("#000000")
Pandemonium.Thickness = 1
Pandemonium.Filled = false
Pandemonium.Size = Vector2.new(40, 20)
Pandemonium.Position = Vector2.new(278, 325)
Pandemonium.ZIndex = 170
Pandemonium.Corner = 7

local PandemoniumBg = Drawing.new("Square")
PandemoniumBg.Visible = false
PandemoniumBg.Transparency = 1
PandemoniumBg.Color = Color3.fromHex("#1b1b2c")
PandemoniumBg.Filled = true
PandemoniumBg.Size = Pandemonium.Size
PandemoniumBg.Position = Pandemonium.Position
PandemoniumBg.ZIndex = 170
PandemoniumBg.Corner = 7

local PandemoniumIndBorder = Drawing.new("Square")
PandemoniumIndBorder.Visible = false
PandemoniumIndBorder.Transparency = 1
PandemoniumIndBorder.Color = Color3.fromHex("#000000")
PandemoniumIndBorder.Thickness = 1
PandemoniumIndBorder.Filled = false
PandemoniumIndBorder.Size = Vector2.new(18, 18)
PandemoniumIndBorder.ZIndex = 172
PandemoniumIndBorder.Corner = 7

local PandemoniumInd = Drawing.new("Square")
PandemoniumInd.Visible = false
PandemoniumInd.Transparency = 1
PandemoniumInd.Color = Color3.fromHex("#20b120")
PandemoniumInd.Filled = true
PandemoniumInd.Size = Vector2.new(18, 18)
PandemoniumInd.ZIndex = 172
PandemoniumInd.Corner = 7

PandemoniumIndBorder.Position = Pandemonium.Position + Vector2.new(1, 1)
PandemoniumInd.Position = Pandemonium.Position + Vector2.new(1, 1)

local PandemoniumLabel = Drawing.new("Text")
PandemoniumLabel.Visible = false
PandemoniumLabel.Text = "Pandemonium"
PandemoniumLabel.Size = 12
PandemoniumLabel.Color = Color3.fromHex("#a1a1a1")
PandemoniumLabel.Outline = true
PandemoniumLabel.Font = Drawing.Fonts.UI
PandemoniumLabel.Position = Pandemonium.Position + Vector2.new(50, 4)
PandemoniumLabel.ZIndex = 171

-- Switch Harbrinder (Chainsmoker)
local HarbrinderIsChecked = false
local Harbrinder = Drawing.new("Square")
Harbrinder.Visible = false
Harbrinder.Transparency = 1
Harbrinder.Color = Color3.fromHex("#000000")
Harbrinder.Thickness = 1
Harbrinder.Filled = false
Harbrinder.Size = Vector2.new(40, 20)
Harbrinder.Position = Vector2.new(278, 355)
Harbrinder.ZIndex = 180
Harbrinder.Corner = 7

local HarbrinderBg = Drawing.new("Square")
HarbrinderBg.Visible = false
HarbrinderBg.Transparency = 1
HarbrinderBg.Color = Color3.fromHex("#1b1b2c")
HarbrinderBg.Filled = true
HarbrinderBg.Size = Harbrinder.Size
HarbrinderBg.Position = Harbrinder.Position
HarbrinderBg.ZIndex = 180
HarbrinderBg.Corner = 7

local HarbrinderIndBorder = Drawing.new("Square")
HarbrinderIndBorder.Visible = false
HarbrinderIndBorder.Transparency = 1
HarbrinderIndBorder.Color = Color3.fromHex("#000000")
HarbrinderIndBorder.Thickness = 1
HarbrinderIndBorder.Filled = false
HarbrinderIndBorder.Size = Vector2.new(18, 18)
HarbrinderIndBorder.ZIndex = 182
HarbrinderIndBorder.Corner = 7

local HarbrinderInd = Drawing.new("Square")
HarbrinderInd.Visible = false
HarbrinderInd.Transparency = 1
HarbrinderInd.Color = Color3.fromHex("#20b120")
HarbrinderInd.Filled = true
HarbrinderInd.Size = Vector2.new(18, 18)
HarbrinderInd.ZIndex = 182
HarbrinderInd.Corner = 7

HarbrinderIndBorder.Position = Harbrinder.Position + Vector2.new(1, 1)
HarbrinderInd.Position = Harbrinder.Position + Vector2.new(1, 1)

local HarbrinderLabel = Drawing.new("Text")
HarbrinderLabel.Visible = false
HarbrinderLabel.Text = "Chainsmoker"
HarbrinderLabel.Size = 12
HarbrinderLabel.Color = Color3.fromHex("#a1a1a1")
HarbrinderLabel.Outline = true
HarbrinderLabel.Font = Drawing.Fonts.UI
HarbrinderLabel.Position = Harbrinder.Position + Vector2.new(50, 4)
HarbrinderLabel.ZIndex = 181

-- Switch A60
local A60IsChecked = false
local A60 = Drawing.new("Square")
A60.Visible = false
A60.Transparency = 1
A60.Color = Color3.fromHex("#000000")
A60.Thickness = 1
A60.Filled = false
A60.Size = Vector2.new(40, 20)
A60.Position = Vector2.new(278, 383)
A60.ZIndex = 190
A60.Corner = 7

local A60Bg = Drawing.new("Square")
A60Bg.Visible = false
A60Bg.Transparency = 1
A60Bg.Color = Color3.fromHex("#1b1b2c")
A60Bg.Filled = true
A60Bg.Size = A60.Size
A60Bg.Position = A60.Position
A60Bg.ZIndex = 190
A60Bg.Corner = 7

local A60IndBorder = Drawing.new("Square")
A60IndBorder.Visible = false
A60IndBorder.Transparency = 1
A60IndBorder.Color = Color3.fromHex("#000000")
A60IndBorder.Thickness = 1
A60IndBorder.Filled = false
A60IndBorder.Size = Vector2.new(18, 18)
A60IndBorder.ZIndex = 192
A60IndBorder.Corner = 7

local A60Ind = Drawing.new("Square")
A60Ind.Visible = false
A60Ind.Transparency = 1
A60Ind.Color = Color3.fromHex("#20b120")
A60Ind.Filled = true
A60Ind.Size = Vector2.new(18, 18)
A60Ind.ZIndex = 192
A60Ind.Corner = 7

A60IndBorder.Position = A60.Position + Vector2.new(1, 1)
A60Ind.Position = A60.Position + Vector2.new(1, 1)

local A60Label = Drawing.new("Text")
A60Label.Visible = false
A60Label.Text = "A-60"
A60Label.Size = 12
A60Label.Color = Color3.fromHex("#a1a1a1")
A60Label.Outline = true
A60Label.Font = Drawing.Fonts.UI
A60Label.Position = A60.Position + Vector2.new(50, 4)
A60Label.ZIndex = 191

-- Switch Painter
local PainterIsChecked = false
local Painter = Drawing.new("Square")
Painter.Visible = false
Painter.Transparency = 1
Painter.Color = Color3.fromHex("#000000")
Painter.Thickness = 1
Painter.Filled = false
Painter.Size = Vector2.new(40, 20)
Painter.Position = Vector2.new(278, 412)
Painter.ZIndex = 200
Painter.Corner = 7

local PainterBg = Drawing.new("Square")
PainterBg.Visible = false
PainterBg.Transparency = 1
PainterBg.Color = Color3.fromHex("#1b1b2c")
PainterBg.Filled = true
PainterBg.Size = Painter.Size
PainterBg.Position = Painter.Position
PainterBg.ZIndex = 200
PainterBg.Corner = 7

local PainterIndBorder = Drawing.new("Square")
PainterIndBorder.Visible = false
PainterIndBorder.Transparency = 1
PainterIndBorder.Color = Color3.fromHex("#000000")
PainterIndBorder.Thickness = 1
PainterIndBorder.Filled = false
PainterIndBorder.Size = Vector2.new(18, 18)
PainterIndBorder.ZIndex = 202
PainterIndBorder.Corner = 7

local PainterInd = Drawing.new("Square")
PainterInd.Visible = false
PainterInd.Transparency = 1
PainterInd.Color = Color3.fromHex("#20b120")
PainterInd.Filled = true
PainterInd.Size = Vector2.new(18, 18)
PainterInd.ZIndex = 202
PainterInd.Corner = 7

PainterIndBorder.Position = Painter.Position + Vector2.new(1, 1)
PainterInd.Position = Painter.Position + Vector2.new(1, 1)

local PainterLabel = Drawing.new("Text")
PainterLabel.Visible = false
PainterLabel.Text = "Painter"
PainterLabel.Size = 12
PainterLabel.Color = Color3.fromHex("#a1a1a1")
PainterLabel.Outline = true
PainterLabel.Font = Drawing.Fonts.UI
PainterLabel.Position = Painter.Position + Vector2.new(50, 4)
PainterLabel.ZIndex = 201

-- Switch Keycard
local KeycardIsChecked = false
local Keycard = Drawing.new("Square")
Keycard.Visible = false
Keycard.Transparency = 1
Keycard.Color = Color3.fromHex("#000000")
Keycard.Thickness = 1
Keycard.Filled = false
Keycard.Size = Vector2.new(40, 20)
Keycard.Position = Vector2.new(611, 173)
Keycard.ZIndex = 210
Keycard.Corner = 7

local KeycardBg = Drawing.new("Square")
KeycardBg.Visible = false
KeycardBg.Transparency = 1
KeycardBg.Color = Color3.fromHex("#1b1b2c")
KeycardBg.Filled = true
KeycardBg.Size = Keycard.Size
KeycardBg.Position = Keycard.Position
KeycardBg.ZIndex = 210
KeycardBg.Corner = 7

local KeycardIndBorder = Drawing.new("Square")
KeycardIndBorder.Visible = false
KeycardIndBorder.Transparency = 1
KeycardIndBorder.Color = Color3.fromHex("#000000")
KeycardIndBorder.Thickness = 1
KeycardIndBorder.Filled = false
KeycardIndBorder.Size = Vector2.new(18, 18)
KeycardIndBorder.ZIndex = 212
KeycardIndBorder.Corner = 7

local KeycardInd = Drawing.new("Square")
KeycardInd.Visible = false
KeycardInd.Transparency = 1
KeycardInd.Color = Color3.fromHex("#2044b1")
KeycardInd.Filled = true
KeycardInd.Size = Vector2.new(18, 18)
KeycardInd.ZIndex = 212
KeycardInd.Corner = 7

KeycardIndBorder.Position = Keycard.Position + Vector2.new(1, 1)
KeycardInd.Position = Keycard.Position + Vector2.new(1, 1)

local KeycardLabel = Drawing.new("Text")
KeycardLabel.Visible = false
KeycardLabel.Text = "Keycard"
KeycardLabel.Size = 12
KeycardLabel.Color = Color3.fromHex("#a1a1a1")
KeycardLabel.Outline = true
KeycardLabel.Font = Drawing.Fonts.UI
KeycardLabel.Position = Keycard.Position + Vector2.new(50, 4)
KeycardLabel.ZIndex = 211

-- Switch DoorESP
local DoorESPIsChecked = false
local DoorESP = Drawing.new("Square")
DoorESP.Visible = false
DoorESP.Transparency = 1
DoorESP.Color = Color3.fromHex("#000000")
DoorESP.Thickness = 1
DoorESP.Filled = false
DoorESP.Size = Vector2.new(40, 20)
DoorESP.Position = Vector2.new(611, 203)
DoorESP.ZIndex = 215
DoorESP.Corner = 7

local DoorESPBg = Drawing.new("Square")
DoorESPBg.Visible = false
DoorESPBg.Transparency = 1
DoorESPBg.Color = Color3.fromHex("#1b1b2c")
DoorESPBg.Filled = true
DoorESPBg.Size = DoorESP.Size
DoorESPBg.Position = DoorESP.Position
DoorESPBg.ZIndex = 215
DoorESPBg.Corner = 7

local DoorESPIndBorder = Drawing.new("Square")
DoorESPIndBorder.Visible = false
DoorESPIndBorder.Transparency = 1
DoorESPIndBorder.Color = Color3.fromHex("#000000")
DoorESPIndBorder.Thickness = 1
DoorESPIndBorder.Filled = false
DoorESPIndBorder.Size = Vector2.new(18, 18)
DoorESPIndBorder.ZIndex = 217
DoorESPIndBorder.Corner = 7

local DoorESPInd = Drawing.new("Square")
DoorESPInd.Visible = false
DoorESPInd.Transparency = 1
DoorESPInd.Color = Color3.fromHex("#ff8c00")
DoorESPInd.Filled = true
DoorESPInd.Size = Vector2.new(18, 18)
DoorESPInd.ZIndex = 217
DoorESPInd.Corner = 7

DoorESPIndBorder.Position = DoorESP.Position + Vector2.new(1, 1)
DoorESPInd.Position = DoorESP.Position + Vector2.new(1, 1)

local DoorESPLabel = Drawing.new("Text")
DoorESPLabel.Visible = false
DoorESPLabel.Text = "Door ESP"
DoorESPLabel.Size = 12
DoorESPLabel.Color = Color3.fromHex("#a1a1a1")
DoorESPLabel.Outline = true
DoorESPLabel.Font = Drawing.Fonts.UI
DoorESPLabel.Position = DoorESP.Position + Vector2.new(50, 4)
DoorESPLabel.ZIndex = 216

-- Line5
local Line5 = Drawing.new("Square")
Line5.Visible = false
Line5.Transparency = 1
Line5.ZIndex = 120
Line5.Color = Color3.fromHex("#10172d")
Line5.Position = TabVisualsContainer.Position + Vector2.new(224, 0)
Line5.Size = Vector2.new(4, 328)
Line5.Filled = true
Line5.Corner = 6

local Line5Border = Drawing.new("Square")
Line5Border.Visible = false
Line5Border.Transparency = 1
Line5Border.ZIndex = 121
Line5Border.Color = Color3.fromHex("#0a0f1f")
Line5Border.Filled = false
Line5Border.Thickness = 1
Line5Border.Position = Line5.Position
Line5Border.Size = Line5.Size
Line5Border.Corner = 6

local EspText = Drawing.new("Text")
EspText.Visible = false
EspText.Transparency = 1
EspText.ZIndex = 220
EspText.Color = Color3.fromHex("#9c9c9c")
EspText.Position = TabVisualsContainer.Position + Vector2.new(10, 10)
EspText.Text = "Nofitications"
EspText.Size = 14
EspText.Center = false
EspText.Outline = false
EspText.Font = Drawing.Fonts.UI

local ESPitems = Drawing.new("Text")
ESPitems.Visible = false
ESPitems.Transparency = 1
ESPitems.ZIndex = 220
ESPitems.Color = Color3.fromHex("#9c9c9c")
ESPitems.Position = TabVisualsContainer.Position + Vector2.new(330, 10)
ESPitems.Text = "ESP items"
ESPitems.Size = 14
ESPitems.Center = false
ESPitems.Outline = false
ESPitems.Font = Drawing.Fonts.UI

-- MiscTABcontainer1
local MiscTABcontainer1 = Drawing.new("Square")
MiscTABcontainer1.Visible = false
MiscTABcontainer1.Transparency = 1
MiscTABcontainer1.ZIndex = 110
MiscTABcontainer1.Color = Color3.fromHex("#0e0e16")
MiscTABcontainer1.Position = MainUIsystem.Position + Vector2.new(210.5, 64)
MiscTABcontainer1.Size = Vector2.new(482, 173)
MiscTABcontainer1.Filled = true
MiscTABcontainer1.Corner = 7

-- Checkbox AutoHideGUI
local AutoHideGUIIsChecked = false
local AutoHideGUI = Drawing.new("Square")
AutoHideGUI.Visible = false
AutoHideGUI.Transparency = 1
AutoHideGUI.Color = Color3.fromHex("#000000")
AutoHideGUI.Thickness = 1
AutoHideGUI.Filled = false
AutoHideGUI.Size = Vector2.new(20, 20)
AutoHideGUI.Position = Vector2.new(271, 153)
AutoHideGUI.ZIndex = 271
AutoHideGUI.Corner = 5

local AutoHideGUIInner = Drawing.new("Square")
AutoHideGUIInner.Visible = false
AutoHideGUIInner.Transparency = 1
AutoHideGUIInner.Color = Color3.fromHex("#4414c8")
AutoHideGUIInner.Filled = true
AutoHideGUIInner.Size = AutoHideGUI.Size
AutoHideGUIInner.Position = AutoHideGUI.Position
AutoHideGUIInner.ZIndex = 270
AutoHideGUIInner.Corner = 5

local AutoHideGUILabel = Drawing.new("Text")
AutoHideGUILabel.Visible = false
AutoHideGUILabel.Text = "AutoHide"
AutoHideGUILabel.Size = 12
AutoHideGUILabel.Outline = true
AutoHideGUILabel.Font = 0
AutoHideGUILabel.Color = Color3.fromHex("#919191")
AutoHideGUILabel.Position = AutoHideGUI.Position + Vector2.new(25, 4)
AutoHideGUILabel.ZIndex = 270

-- Checkbox WatermarkButton
local WatermarkButtonIsChecked = false
local WatermarkButton = Drawing.new("Square")
WatermarkButton.Visible = false
WatermarkButton.Transparency = 1
WatermarkButton.Color = Color3.fromHex("#000000")
WatermarkButton.Thickness = 1
WatermarkButton.Filled = false
WatermarkButton.Size = Vector2.new(20, 20)
WatermarkButton.Position = Vector2.new(271, 184.5)
WatermarkButton.ZIndex = 281
WatermarkButton.Corner = 5

local WatermarkButtonInner = Drawing.new("Square")
WatermarkButtonInner.Visible = false
WatermarkButtonInner.Transparency = 1
WatermarkButtonInner.Color = Color3.fromHex("#4414c8")
WatermarkButtonInner.Filled = true
WatermarkButtonInner.Size = WatermarkButton.Size
WatermarkButtonInner.Position = WatermarkButton.Position
WatermarkButtonInner.ZIndex = 280
WatermarkButtonInner.Corner = 5

local WatermarkButtonLabel = Drawing.new("Text")
WatermarkButtonLabel.Visible = false
WatermarkButtonLabel.Text = "Watermark"
WatermarkButtonLabel.Size = 12
WatermarkButtonLabel.Outline = true
WatermarkButtonLabel.Font = 0
WatermarkButtonLabel.Color = Color3.fromHex("#999999")
WatermarkButtonLabel.Position = WatermarkButton.Position + Vector2.new(25, 4)
WatermarkButtonLabel.ZIndex = 280

-- Checkbox AutoRescanButton
local AutoRescanButtonIsChecked = false
local AutoRescanButton = Drawing.new("Square")
AutoRescanButton.Visible = false
AutoRescanButton.Transparency = 1
AutoRescanButton.Color = Color3.fromHex("#24233e")
AutoRescanButton.Thickness = 1
AutoRescanButton.Filled = false
AutoRescanButton.Size = Vector2.new(20, 20)
AutoRescanButton.Position = TabVisualsContainer.Position + Vector2.new(403.5, 150)
AutoRescanButton.ZIndex = 291
AutoRescanButton.Corner = 10

local AutoRescanButtonInner = Drawing.new("Square")
AutoRescanButtonInner.Visible = false
AutoRescanButtonInner.Transparency = 1
AutoRescanButtonInner.Color = Color3.fromHex("#0a638f")
AutoRescanButtonInner.Filled = true
AutoRescanButtonInner.Size = AutoRescanButton.Size
AutoRescanButtonInner.Position = AutoRescanButton.Position
AutoRescanButtonInner.ZIndex = 290
AutoRescanButtonInner.Corner = 10

local AutoRescanButtonLabel = Drawing.new("Text")
AutoRescanButtonLabel.Visible = false
AutoRescanButtonLabel.Text = "AutoRescan"
AutoRescanButtonLabel.Size = 12
AutoRescanButtonLabel.Outline = true
AutoRescanButtonLabel.Font = 0
AutoRescanButtonLabel.Color = Color3.fromHex("#b3b3b3")
AutoRescanButtonLabel.Position = AutoRescanButton.Position + Vector2.new(-90, 4)
AutoRescanButtonLabel.ZIndex = 290

-- Slider AutoRescanInterval
local AutoRescanSlider = Drawing.new("Square")
AutoRescanSlider.Visible = false
AutoRescanSlider.Transparency = 1
AutoRescanSlider.Color = Color3.fromHex("#444444")
AutoRescanSlider.Filled = true
AutoRescanSlider.Size = Vector2.new(90, 10)
AutoRescanSlider.Position = TabVisualsContainer.Position + Vector2.new(438.5, 155)
AutoRescanSlider.ZIndex = 300
AutoRescanSlider.Corner = 10

local AutoRescanSliderKnob = Drawing.new("Square")
AutoRescanSliderKnob.Visible = false
AutoRescanSliderKnob.Transparency = 1
AutoRescanSliderKnob.Color = Color3.fromHex("#1a1952")
AutoRescanSliderKnob.Filled = true
AutoRescanSliderKnob.Size = Vector2.new(20, 20)
AutoRescanSliderKnob.Position = AutoRescanSlider.Position + Vector2.new((90 * ((Settings.autoRescanInterval - 1) / 29)) - 10, -5)
AutoRescanSliderKnob.ZIndex = 301
AutoRescanSliderKnob.Corner = 100

local AutoRescanValueText = Drawing.new("Text")
AutoRescanValueText.Visible = false
AutoRescanValueText.Text = tostring(Settings.autoRescanInterval) .. "s"
AutoRescanValueText.Size = 14
AutoRescanValueText.Center = true
AutoRescanValueText.Outline = true
AutoRescanValueText.Color = Color3.new(1, 1, 1)
AutoRescanValueText.Position = AutoRescanSlider.Position + Vector2.new(45, -12)
AutoRescanValueText.ZIndex = 302

-- Keybind KeybindForceRescan
local KeybindForceRescan = Drawing.new("Square")
KeybindForceRescan.Visible = false
KeybindForceRescan.Transparency = 1
KeybindForceRescan.Color = Color3.fromHex("#101023")
KeybindForceRescan.Filled = true
KeybindForceRescan.Size = Vector2.new(68, 19)
KeybindForceRescan.Position = TabVisualsContainer.Position + Vector2.new(403.5, 182)
KeybindForceRescan.ZIndex = 310
KeybindForceRescan.Corner = 8

local KeybindForceRescanBorder = Drawing.new("Square")
KeybindForceRescanBorder.Visible = false
KeybindForceRescanBorder.Transparency = 1
KeybindForceRescanBorder.Color = Color3.fromHex("#000000")
KeybindForceRescanBorder.Thickness = 1
KeybindForceRescanBorder.Filled = false
KeybindForceRescanBorder.Size = KeybindForceRescan.Size
KeybindForceRescanBorder.Position = KeybindForceRescan.Position
KeybindForceRescanBorder.ZIndex = 311
KeybindForceRescanBorder.Corner = 8

local KeybindForceRescanText = Drawing.new("Text")
KeybindForceRescanText.Text = "F5"
KeybindForceRescanText.Size = 12
KeybindForceRescanText.Center = true
KeybindForceRescanText.Outline = true
KeybindForceRescanText.Font = 0
KeybindForceRescanText.Color = Color3.fromHex("#969696")
KeybindForceRescanText.Position = KeybindForceRescan.Position + Vector2.new(34, 9.5)
KeybindForceRescanText.Visible = false
KeybindForceRescanText.ZIndex = 312

local KeybindForceRescanKey = 0x74
local KeybindForceRescanIsListening = false

local ForceRescanLabel = Drawing.new("Text")
ForceRescanLabel.Visible = false
ForceRescanLabel.Text = "Force Rescan"
ForceRescanLabel.Size = 12
ForceRescanLabel.Outline = true
ForceRescanLabel.Font = 0
ForceRescanLabel.Color = Color3.fromHex("#b3b3b3")
ForceRescanLabel.Position = KeybindForceRescan.Position + Vector2.new(-100, 4)
ForceRescanLabel.ZIndex = 310

local sliderDragging = false
local currentTab = "Home"

-- KeyNames
local KeyNames = {
    [0x30]="0",[0x31]="1",[0x32]="2",[0x33]="3",[0x34]="4",
    [0x35]="5",[0x36]="6",[0x37]="7",[0x38]="8",[0x39]="9",
    [0x01]="LeftMouse",[0x02]="RightMouse",[0x04]="MiddleMouse",
    [0x08]="Backspace",[0x09]="Tab",[0x0D]="Enter",
    [0x10]="Shift",[0x11]="Ctrl",[0x12]="Alt",
    [0x13]="Pause",[0x14]="CapsLock",[0x1B]="Esc",
    [0x20]="Space",[0x21]="PageUp",[0x22]="PageDown",
    [0x23]="End",[0x24]="Home",[0x25]="Left",
    [0x26]="Up",[0x27]="Right",[0x28]="Down",
    [0x2D]="Insert",[0x2E]="Delete",
    [0x41]="A",[0x42]="B",[0x43]="C",[0x44]="D",[0x45]="E",
    [0x46]="F",[0x47]="G",[0x48]="H",[0x49]="I",[0x4A]="J",
    [0x4B]="K",[0x4C]="L",[0x4D]="M",[0x4E]="N",[0x4F]="O",
    [0x50]="P",[0x51]="Q",[0x52]="R",[0x53]="S",[0x54]="T",
    [0x55]="U",[0x56]="V",[0x57]="W",[0x58]="X",[0x59]="Y",
    [0x5A]="Z",[0x60]="Numpad0",[0x61]="Numpad1",[0x62]="Numpad2",
    [0x63]="Numpad3",[0x64]="Numpad4",[0x65]="Numpad5",[0x66]="Numpad6",
    [0x67]="Numpad7",[0x68]="Numpad8",[0x69]="Numpad9",
    [0x70]="F1",[0x71]="F2",[0x72]="F3",[0x73]="F4",
    [0x74]="F5",[0x75]="F6",[0x76]="F7",[0x77]="F8",
    [0x78]="F9",[0x79]="F10",[0x7A]="F11",[0x7B]="F12"
}

-- AllGUIElements
local AllGUIElements = {
    MainUIsystem, MainUIsystemBorder, Line, LineBorder, Line1, Line1Border,
    RATHUBlogo, Line2, Line2Border, HOMEtabB, HOMEtabBText,
    TabVisualsB, TabVisualsBText, MiscTAB, MiscTABText, SettingsTAB, SettingsTABText,
    TabHomeContainer1, WorkGames1, PressureWORK,
    TabVisualsContainer,
    Angler, AnglerBg, AnglerIndBorder, AnglerInd, AnglerLabel,
    Froger, FrogerBg, FrogerIndBorder, FrogerInd, FrogerLabel,
    Pinkie, PinkieBg, PinkieIndBorder, PinkieInd, PinkieLabel,
    Blitz, BlitzBg, BlitzIndBorder, BlitzInd, BlitzLabel,
    Pandemonium, PandemoniumBg, PandemoniumIndBorder, PandemoniumInd, PandemoniumLabel,
    Harbrinder, HarbrinderBg, HarbrinderIndBorder, HarbrinderInd, HarbrinderLabel,
    A60, A60Bg, A60IndBorder, A60Ind, A60Label,
    Painter, PainterBg, PainterIndBorder, PainterInd, PainterLabel,
    Keycard, KeycardBg, KeycardIndBorder, KeycardInd, KeycardLabel,
    DoorESP, DoorESPBg, DoorESPIndBorder, DoorESPInd, DoorESPLabel,
    Line5, Line5Border, EspText, ESPitems,
    MiscTABcontainer1, AutoHideGUI, AutoHideGUIInner, AutoHideGUILabel,
    WatermarkButton, WatermarkButtonInner, WatermarkButtonLabel,
    AutoRescanButton, AutoRescanButtonInner, AutoRescanButtonLabel,
    AutoRescanSlider, AutoRescanSliderKnob, AutoRescanValueText,
    KeybindForceRescan, KeybindForceRescanBorder, KeybindForceRescanText, ForceRescanLabel
}

-- Functions
local function TabHomeContainerSetVisible(visible)
    TabHomeContainer1.Visible = visible
    WorkGames1.Visible = visible
    PressureWORK.Visible = visible
end

local function TabTabVisualsContainerSetVisible(visible)
    TabVisualsContainer.Visible = visible
    if Angler then Angler.Visible = visible end
    if AnglerBg then AnglerBg.Visible = visible end
    if AnglerIndBorder then AnglerIndBorder.Visible = visible end
    if AnglerInd then AnglerInd.Visible = visible and AnglerIsChecked end
    if AnglerLabel then AnglerLabel.Visible = visible end
    if Froger then Froger.Visible = visible end
    if FrogerBg then FrogerBg.Visible = visible end
    if FrogerIndBorder then FrogerIndBorder.Visible = visible end
    if FrogerInd then FrogerInd.Visible = visible and FrogerIsChecked end
    if FrogerLabel then FrogerLabel.Visible = visible end
    if Pinkie then Pinkie.Visible = visible end
    if PinkieBg then PinkieBg.Visible = visible end
    if PinkieIndBorder then PinkieIndBorder.Visible = visible end
    if PinkieInd then PinkieInd.Visible = visible and PinkieIsChecked end
    if PinkieLabel then PinkieLabel.Visible = visible end
    if Blitz then Blitz.Visible = visible end
    if BlitzBg then BlitzBg.Visible = visible end
    if BlitzIndBorder then BlitzIndBorder.Visible = visible end
    if BlitzInd then BlitzInd.Visible = visible and BlitzIsChecked end
    if BlitzLabel then BlitzLabel.Visible = visible end
    if Pandemonium then Pandemonium.Visible = visible end
    if PandemoniumBg then PandemoniumBg.Visible = visible end
    if PandemoniumIndBorder then PandemoniumIndBorder.Visible = visible end
    if PandemoniumInd then PandemoniumInd.Visible = visible and PandemoniumIsChecked end
    if PandemoniumLabel then PandemoniumLabel.Visible = visible end
    if Harbrinder then Harbrinder.Visible = visible end
    if HarbrinderBg then HarbrinderBg.Visible = visible end
    if HarbrinderIndBorder then HarbrinderIndBorder.Visible = visible end
    if HarbrinderInd then HarbrinderInd.Visible = visible and HarbrinderIsChecked end
    if HarbrinderLabel then HarbrinderLabel.Visible = visible end
    if A60 then A60.Visible = visible end
    if A60Bg then A60Bg.Visible = visible end
    if A60IndBorder then A60IndBorder.Visible = visible end
    if A60Ind then A60Ind.Visible = visible and A60IsChecked end
    if A60Label then A60Label.Visible = visible end
    if Painter then Painter.Visible = visible end
    if PainterBg then PainterBg.Visible = visible end
    if PainterIndBorder then PainterIndBorder.Visible = visible end
    if PainterInd then PainterInd.Visible = visible and PainterIsChecked end
    if PainterLabel then PainterLabel.Visible = visible end
    if Keycard then Keycard.Visible = visible end
    if KeycardBg then KeycardBg.Visible = visible end
    if KeycardIndBorder then KeycardIndBorder.Visible = visible end
    if KeycardInd then KeycardInd.Visible = visible and KeycardIsChecked end
    if KeycardLabel then KeycardLabel.Visible = visible end
    if DoorESP then DoorESP.Visible = visible end
    if DoorESPBg then DoorESPBg.Visible = visible end
    if DoorESPIndBorder then DoorESPIndBorder.Visible = visible end
    if DoorESPInd then DoorESPInd.Visible = visible and DoorESPIsChecked end
    if DoorESPLabel then DoorESPLabel.Visible = visible end
    if Line5 then Line5.Visible = visible end
    if Line5Border then Line5Border.Visible = visible end
    if EspText then EspText.Visible = visible end
    if ESPitems then ESPitems.Visible = visible end
    if AutoRescanButton then
        AutoRescanButton.Visible = visible
        if AutoRescanButtonInner then AutoRescanButtonInner.Visible = visible and AutoRescanButtonIsChecked end
        if AutoRescanButtonLabel then AutoRescanButtonLabel.Visible = visible end
    end
    if AutoRescanSlider then
        AutoRescanSlider.Visible = visible
        if AutoRescanSliderKnob then AutoRescanSliderKnob.Visible = visible end
        if AutoRescanValueText then AutoRescanValueText.Visible = visible end
    end
    if KeybindForceRescan then
        KeybindForceRescan.Visible = visible
        if KeybindForceRescanBorder then KeybindForceRescanBorder.Visible = visible end
        if KeybindForceRescanText then KeybindForceRescanText.Visible = visible end
        if ForceRescanLabel then ForceRescanLabel.Visible = visible end
    end
end

local function TabMiscTABcontainer1SetVisible(visible)
    MiscTABcontainer1.Visible = visible
    if AutoHideGUI then AutoHideGUI.Visible = visible end
    if AutoHideGUIInner then AutoHideGUIInner.Visible = visible and AutoHideGUIIsChecked end
    if AutoHideGUILabel then AutoHideGUILabel.Visible = visible end
    if WatermarkButton then WatermarkButton.Visible = visible end
    if WatermarkButtonInner then WatermarkButtonInner.Visible = visible and WatermarkButtonIsChecked end
    if WatermarkButtonLabel then WatermarkButtonLabel.Visible = visible end
end

local function ToggleGUI()
    Settings.guiVisible = not Settings.guiVisible
    for _, element in ipairs(AllGUIElements) do
        if element and element.Visible ~= nil then
            element.Visible = Settings.guiVisible
        end
    end
    if not Settings.guiVisible then
        TabHomeContainerSetVisible(false)
        TabTabVisualsContainerSetVisible(false)
        TabMiscTABcontainer1SetVisible(false)
    else
        if currentTab == "Home" then
            TabHomeContainerSetVisible(true)
            TabTabVisualsContainerSetVisible(false)
            TabMiscTABcontainer1SetVisible(false)
        elseif currentTab == "Visuals" then
            TabHomeContainerSetVisible(false)
            TabTabVisualsContainerSetVisible(true)
            TabMiscTABcontainer1SetVisible(false)
        elseif currentTab == "Misc" then
            TabHomeContainerSetVisible(false)
            TabTabVisualsContainerSetVisible(false)
            TabMiscTABcontainer1SetVisible(true)
        end
    end
end

-- Set initial visibility
MainUIsystem.Visible = Settings.guiVisible
MainUIsystemBorder.Visible = Settings.guiVisible
Line.Visible = Settings.guiVisible
LineBorder.Visible = Settings.guiVisible
Line1.Visible = Settings.guiVisible
Line1Border.Visible = Settings.guiVisible
RATHUBlogo.Visible = Settings.guiVisible
Line2.Visible = Settings.guiVisible
Line2Border.Visible = Settings.guiVisible
HOMEtabB.Visible = Settings.guiVisible
HOMEtabBText.Visible = Settings.guiVisible
TabVisualsB.Visible = Settings.guiVisible
TabVisualsBText.Visible = Settings.guiVisible
MiscTAB.Visible = Settings.guiVisible
MiscTABText.Visible = Settings.guiVisible
SettingsTAB.Visible = Settings.guiVisible
SettingsTABText.Visible = Settings.guiVisible

-- Input Handling
local dragging = nil
local dragStart = nil
local startPos = nil
local lastMouse1 = false
local lastF1 = false
local lastRescanKey = false

spawn(function()
    while true do
        wait(0.01)
        if isrbxactive() then
            local mouse1 = ismouse1pressed()
            local mPos = Vector2.new(Mouse.X, Mouse.Y)

            local function clickedOn(element, pos)
                return element.Visible
                    and pos.X >= element.Position.X and pos.X <= element.Position.X + element.Size.X
                    and pos.Y >= element.Position.Y and pos.Y <= element.Position.Y + element.Size.Y
            end

            if mouse1 and not lastMouse1 then
                if clickedOn(HOMEtabB, mPos) then
                    currentTab = "Home"
                    TabHomeContainerSetVisible(true)
                    TabTabVisualsContainerSetVisible(false)
                    TabMiscTABcontainer1SetVisible(false)

                elseif clickedOn(TabVisualsB, mPos) then
                    currentTab = "Visuals"
                    TabHomeContainerSetVisible(false)
                    TabTabVisualsContainerSetVisible(true)
                    TabMiscTABcontainer1SetVisible(false)

                elseif clickedOn(MiscTAB, mPos) then
                    currentTab = "Misc"
                    TabHomeContainerSetVisible(false)
                    TabTabVisualsContainerSetVisible(false)
                    TabMiscTABcontainer1SetVisible(true)

                elseif clickedOn(MainUIsystem, mPos) and mPos.Y <= MainUIsystem.Position.Y + 43 then
                    dragging = MainUIsystem
                    dragStart = mPos
                    startPos = MainUIsystem.Position

                elseif clickedOn(Angler, mPos) or clickedOn(AnglerBg, mPos) then
                    AnglerIsChecked = not AnglerIsChecked
                    Settings.notificationsEnabled.Angler = AnglerIsChecked
                    AnglerInd.Visible = AnglerIsChecked
                    if AnglerIsChecked then
                        AnglerIndBorder.Position = Angler.Position + Vector2.new(21, 1)
                        AnglerInd.Position = Angler.Position + Vector2.new(21, 1)
                    else
                        AnglerIndBorder.Position = Angler.Position + Vector2.new(1, 1)
                        AnglerInd.Position = Angler.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(Froger, mPos) or clickedOn(FrogerBg, mPos) then
                    FrogerIsChecked = not FrogerIsChecked
                    Settings.notificationsEnabled.Froger = FrogerIsChecked
                    FrogerInd.Visible = FrogerIsChecked
                    if FrogerIsChecked then
                        FrogerIndBorder.Position = Froger.Position + Vector2.new(21, 1)
                        FrogerInd.Position = Froger.Position + Vector2.new(21, 1)
                    else
                        FrogerIndBorder.Position = Froger.Position + Vector2.new(1, 1)
                        FrogerInd.Position = Froger.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(Pinkie, mPos) or clickedOn(PinkieBg, mPos) then
                    PinkieIsChecked = not PinkieIsChecked
                    Settings.notificationsEnabled.Pinkie = PinkieIsChecked
                    PinkieInd.Visible = PinkieIsChecked
                    if PinkieIsChecked then
                        PinkieIndBorder.Position = Pinkie.Position + Vector2.new(21, 1)
                        PinkieInd.Position = Pinkie.Position + Vector2.new(21, 1)
                    else
                        PinkieIndBorder.Position = Pinkie.Position + Vector2.new(1, 1)
                        PinkieInd.Position = Pinkie.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(Blitz, mPos) or clickedOn(BlitzBg, mPos) then
                    BlitzIsChecked = not BlitzIsChecked
                    Settings.notificationsEnabled.Blitz = BlitzIsChecked
                    BlitzInd.Visible = BlitzIsChecked
                    if BlitzIsChecked then
                        BlitzIndBorder.Position = Blitz.Position + Vector2.new(21, 1)
                        BlitzInd.Position = Blitz.Position + Vector2.new(21, 1)
                    else
                        BlitzIndBorder.Position = Blitz.Position + Vector2.new(1, 1)
                        BlitzInd.Position = Blitz.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(Pandemonium, mPos) or clickedOn(PandemoniumBg, mPos) then
                    PandemoniumIsChecked = not PandemoniumIsChecked
                    Settings.notificationsEnabled.Pandemonium = PandemoniumIsChecked
                    PandemoniumInd.Visible = PandemoniumIsChecked
                    if PandemoniumIsChecked then
                        PandemoniumIndBorder.Position = Pandemonium.Position + Vector2.new(21, 1)
                        PandemoniumInd.Position = Pandemonium.Position + Vector2.new(21, 1)
                    else
                        PandemoniumIndBorder.Position = Pandemonium.Position + Vector2.new(1, 1)
                        PandemoniumInd.Position = Pandemonium.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(Harbrinder, mPos) or clickedOn(HarbrinderBg, mPos) then
                    HarbrinderIsChecked = not HarbrinderIsChecked
                    Settings.notificationsEnabled.Chainsmoker = HarbrinderIsChecked
                    HarbrinderInd.Visible = HarbrinderIsChecked
                    if HarbrinderIsChecked then
                        HarbrinderIndBorder.Position = Harbrinder.Position + Vector2.new(21, 1)
                        HarbrinderInd.Position = Harbrinder.Position + Vector2.new(21, 1)
                    else
                        HarbrinderIndBorder.Position = Harbrinder.Position + Vector2.new(1, 1)
                        HarbrinderInd.Position = Harbrinder.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(A60, mPos) or clickedOn(A60Bg, mPos) then
                    A60IsChecked = not A60IsChecked
                    Settings.notificationsEnabled["A-60"] = A60IsChecked
                    A60Ind.Visible = A60IsChecked
                    if A60IsChecked then
                        A60IndBorder.Position = A60.Position + Vector2.new(21, 1)
                        A60Ind.Position = A60.Position + Vector2.new(21, 1)
                    else
                        A60IndBorder.Position = A60.Position + Vector2.new(1, 1)
                        A60Ind.Position = A60.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(Painter, mPos) or clickedOn(PainterBg, mPos) then
                    PainterIsChecked = not PainterIsChecked
                    Settings.notificationsEnabled.Painter = PainterIsChecked
                    PainterInd.Visible = PainterIsChecked
                    if PainterIsChecked then
                        PainterIndBorder.Position = Painter.Position + Vector2.new(21, 1)
                        PainterInd.Position = Painter.Position + Vector2.new(21, 1)
                    else
                        PainterIndBorder.Position = Painter.Position + Vector2.new(1, 1)
                        PainterInd.Position = Painter.Position + Vector2.new(1, 1)
                    end

                elseif clickedOn(Keycard, mPos) or clickedOn(KeycardBg, mPos) then
                    KeycardIsChecked = not KeycardIsChecked
                    KeycardInd.Visible = KeycardIsChecked
                    if KeycardIsChecked then
                        KeycardIndBorder.Position = Keycard.Position + Vector2.new(21, 1)
                        KeycardInd.Position = Keycard.Position + Vector2.new(21, 1)
                        StartKeycardESP()
                    else
                        KeycardIndBorder.Position = Keycard.Position + Vector2.new(1, 1)
                        KeycardInd.Position = Keycard.Position + Vector2.new(1, 1)
                        CleanupKeycardESP()
                    end

                elseif clickedOn(DoorESP, mPos) or clickedOn(DoorESPBg, mPos) then
                    DoorESPIsChecked = not DoorESPIsChecked
                    DoorESPInd.Visible = DoorESPIsChecked
                    if DoorESPIsChecked then
                        DoorESPIndBorder.Position = DoorESP.Position + Vector2.new(21, 1)
                        DoorESPInd.Position = DoorESP.Position + Vector2.new(21, 1)
                        StartDoorESP()
                    else
                        DoorESPIndBorder.Position = DoorESP.Position + Vector2.new(1, 1)
                        DoorESPInd.Position = DoorESP.Position + Vector2.new(1, 1)
                        CleanupDoorESP()
                    end

                elseif clickedOn(AutoHideGUI, mPos) then
                    AutoHideGUIIsChecked = not AutoHideGUIIsChecked
                    AutoHideGUIInner.Visible = AutoHideGUIIsChecked
                    AutoHideSystem.enabled = AutoHideGUIIsChecked
                    print("AutoHide: " .. tostring(AutoHideGUIIsChecked))

                elseif clickedOn(WatermarkButton, mPos) then
                    WatermarkButtonIsChecked = not WatermarkButtonIsChecked
                    WatermarkButtonInner.Visible = WatermarkButtonIsChecked
                    WatermarkSystem.enabled = WatermarkButtonIsChecked
                    Settings.watermarkEnabled = WatermarkButtonIsChecked
                    WatermarkSystem:SetVisible(WatermarkButtonIsChecked)
                    print("Watermark: " .. tostring(WatermarkButtonIsChecked))

                elseif clickedOn(AutoRescanButton, mPos) then
                    AutoRescanButtonIsChecked = not AutoRescanButtonIsChecked
                    AutoRescanButtonInner.Visible = AutoRescanButtonIsChecked and TabVisualsContainer.Visible
                    Settings.autoRescanEnabled = AutoRescanButtonIsChecked
                    if AutoRescanButtonIsChecked then
                        lastRescanTime = os.clock()
                    end
                    print("AutoRescan: " .. (AutoRescanButtonIsChecked and "ENABLED" or "DISABLED"))

                elseif clickedOn(AutoRescanSlider, mPos) or (AutoRescanSliderKnob.Visible and clickedOn(AutoRescanSliderKnob, mPos)) then
                    sliderDragging = true

                elseif clickedOn(KeybindForceRescan, mPos) then
                    KeybindForceRescanIsListening = not KeybindForceRescanIsListening
                    if KeybindForceRescanIsListening then
                        KeybindForceRescanText.Text = "..."
                        KeybindForceRescanText.Color = Color3.fromHex("#00ff00")
                    end
                end
            end

            if not mouse1 and lastMouse1 then
                dragging = nil
                sliderDragging = false
            end

            if sliderDragging and mouse1 then
                local sliderX = AutoRescanSlider.Position.X
                local sliderWidth = AutoRescanSlider.Size.X
                local relativeX = math.clamp(mPos.X - sliderX, 0, sliderWidth)
                local percent = relativeX / sliderWidth
                Settings.autoRescanInterval = math.floor(1 + percent * 29)
                AutoRescanSliderKnob.Position = AutoRescanSlider.Position + Vector2.new((sliderWidth * percent) - 10, -5)
                AutoRescanValueText.Text = tostring(Settings.autoRescanInterval) .. "s"
            end

            if KeybindForceRescanIsListening then
                for keycode = 0x08, 0x7B do
                    if iskeypressed(keycode) and keycode ~= 0x70 then
                        KeybindForceRescanKey = keycode
                        KeybindForceRescanText.Text = KeyNames[keycode] or "Key"
                        KeybindForceRescanText.Color = Color3.fromHex("#969696")
                        KeybindForceRescanIsListening = false
                        print("Force Rescan keybind: " .. (KeyNames[keycode] or tostring(keycode)))
                        break
                    end
                end
            end

            local rescanKeyPressed = iskeypressed(KeybindForceRescanKey)
            if rescanKeyPressed and not lastRescanKey then
                if Settings.keycardESPEnabled then
                    ForceRescanESP()
                    print("Force rescan triggered!")
                end
            end
            lastRescanKey = rescanKeyPressed

            if dragging == MainUIsystem then
                local delta = mPos - dragStart
                local newPos = startPos + delta
                MainUIsystem.Position = newPos
                MainUIsystemBorder.Position = newPos
                Line.Position = newPos + Vector2.new(188.5, 0)
                LineBorder.Position = Line.Position
                Line1.Position = newPos + Vector2.new(0, 43)
                Line1Border.Position = Line1.Position
                RATHUBlogo.Position = newPos + Vector2.new(71.5, 15)
                Line2.Position = newPos + Vector2.new(191.5, 43)
                Line2Border.Position = Line2.Position
                HOMEtabB.Position = newPos + Vector2.new(9.5, 51)
                HOMEtabBText.Position = HOMEtabB.Position + Vector2.new(172/2, 43/2)
                TabVisualsB.Position = newPos + Vector2.new(9.5, 103)
                TabVisualsBText.Position = TabVisualsB.Position + Vector2.new(172/2, 43/2)
                MiscTAB.Position = newPos + Vector2.new(9.5, 154)
                MiscTABText.Position = MiscTAB.Position + Vector2.new(172/2, 43/2)
                SettingsTAB.Position = newPos + Vector2.new(9.5, 369)
                SettingsTABText.Position = SettingsTAB.Position + Vector2.new(172/2, 43/2)

                TabHomeContainer1.Position = newPos + Vector2.new(476.5, 57.5)
                WorkGames1.Position = TabHomeContainer1.Position + Vector2.new(21, 23.5)
                PressureWORK.Position = TabHomeContainer1.Position + Vector2.new(39, 14.5)

                TabVisualsContainer.Position = newPos + Vector2.new(207.5, 58)

                -- Notifications (левая колонка)
                Angler.Position = TabVisualsContainer.Position + Vector2.new(31, 39)
                AnglerBg.Position = Angler.Position
                AnglerLabel.Position = Angler.Position + Vector2.new(50, 4)
                if AnglerIsChecked then AnglerIndBorder.Position = Angler.Position + Vector2.new(21,1) AnglerInd.Position = Angler.Position + Vector2.new(21,1)
                else AnglerIndBorder.Position = Angler.Position + Vector2.new(1,1) AnglerInd.Position = Angler.Position + Vector2.new(1,1) end

                Froger.Position = TabVisualsContainer.Position + Vector2.new(31, 73)
                FrogerBg.Position = Froger.Position
                FrogerLabel.Position = Froger.Position + Vector2.new(50, 4)
                if FrogerIsChecked then FrogerIndBorder.Position = Froger.Position + Vector2.new(21,1) FrogerInd.Position = Froger.Position + Vector2.new(21,1)
                else FrogerIndBorder.Position = Froger.Position + Vector2.new(1,1) FrogerInd.Position = Froger.Position + Vector2.new(1,1) end

                Pinkie.Position = TabVisualsContainer.Position + Vector2.new(31, 103)
                PinkieBg.Position = Pinkie.Position
                PinkieLabel.Position = Pinkie.Position + Vector2.new(50, 4)
                if PinkieIsChecked then PinkieIndBorder.Position = Pinkie.Position + Vector2.new(21,1) PinkieInd.Position = Pinkie.Position + Vector2.new(21,1)
                else PinkieIndBorder.Position = Pinkie.Position + Vector2.new(1,1) PinkieInd.Position = Pinkie.Position + Vector2.new(1,1) end

                Blitz.Position = TabVisualsContainer.Position + Vector2.new(31, 134)
                BlitzBg.Position = Blitz.Position
                BlitzLabel.Position = Blitz.Position + Vector2.new(50, 4)
                if BlitzIsChecked then BlitzIndBorder.Position = Blitz.Position + Vector2.new(21,1) BlitzInd.Position = Blitz.Position + Vector2.new(21,1)
                else BlitzIndBorder.Position = Blitz.Position + Vector2.new(1,1) BlitzInd.Position = Blitz.Position + Vector2.new(1,1) end

                Pandemonium.Position = TabVisualsContainer.Position + Vector2.new(31, 161)
                PandemoniumBg.Position = Pandemonium.Position
                PandemoniumLabel.Position = Pandemonium.Position + Vector2.new(50, 4)
                if PandemoniumIsChecked then PandemoniumIndBorder.Position = Pandemonium.Position + Vector2.new(21,1) PandemoniumInd.Position = Pandemonium.Position + Vector2.new(21,1)
                else PandemoniumIndBorder.Position = Pandemonium.Position + Vector2.new(1,1) PandemoniumInd.Position = Pandemonium.Position + Vector2.new(1,1) end

                Harbrinder.Position = TabVisualsContainer.Position + Vector2.new(31, 192)
                HarbrinderBg.Position = Harbrinder.Position
                HarbrinderLabel.Position = Harbrinder.Position + Vector2.new(50, 4)
                if HarbrinderIsChecked then HarbrinderIndBorder.Position = Harbrinder.Position + Vector2.new(21,1) HarbrinderInd.Position = Harbrinder.Position + Vector2.new(21,1)
                else HarbrinderIndBorder.Position = Harbrinder.Position + Vector2.new(1,1) HarbrinderInd.Position = Harbrinder.Position + Vector2.new(1,1) end

                A60.Position = TabVisualsContainer.Position + Vector2.new(31, 220)
                A60Bg.Position = A60.Position
                A60Label.Position = A60.Position + Vector2.new(50, 4)
                if A60IsChecked then A60IndBorder.Position = A60.Position + Vector2.new(21,1) A60Ind.Position = A60.Position + Vector2.new(21,1)
                else A60IndBorder.Position = A60.Position + Vector2.new(1,1) A60Ind.Position = A60.Position + Vector2.new(1,1) end

                Painter.Position = TabVisualsContainer.Position + Vector2.new(31, 274)
                PainterBg.Position = Painter.Position
                PainterLabel.Position = Painter.Position + Vector2.new(50, 4)
                if PainterIsChecked then PainterIndBorder.Position = Painter.Position + Vector2.new(21,1) PainterInd.Position = Painter.Position + Vector2.new(21,1)
                else PainterIndBorder.Position = Painter.Position + Vector2.new(1,1) PainterInd.Position = Painter.Position + Vector2.new(1,1) end

                -- ESP Items (правая колонка)
                Keycard.Position = TabVisualsContainer.Position + Vector2.new(244, 36)
                KeycardBg.Position = Keycard.Position
                KeycardLabel.Position = Keycard.Position + Vector2.new(50, 4)
                if KeycardIsChecked then KeycardIndBorder.Position = Keycard.Position + Vector2.new(21,1) KeycardInd.Position = Keycard.Position + Vector2.new(21,1)
                else KeycardIndBorder.Position = Keycard.Position + Vector2.new(1,1) KeycardInd.Position = Keycard.Position + Vector2.new(1,1) end

                DoorESP.Position = TabVisualsContainer.Position + Vector2.new(244, 66)
                DoorESPBg.Position = DoorESP.Position
                DoorESPLabel.Position = DoorESP.Position + Vector2.new(50, 4)
                if DoorESPIsChecked then DoorESPIndBorder.Position = DoorESP.Position + Vector2.new(21,1) DoorESPInd.Position = DoorESP.Position + Vector2.new(21,1)
                else DoorESPIndBorder.Position = DoorESP.Position + Vector2.new(1,1) DoorESPInd.Position = DoorESP.Position + Vector2.new(1,1) end

                Line5.Position = TabVisualsContainer.Position + Vector2.new(224, 0)
                Line5Border.Position = Line5.Position
                EspText.Position = TabVisualsContainer.Position + Vector2.new(10, 10)
                ESPitems.Position = TabVisualsContainer.Position + Vector2.new(330, 10)

                AutoRescanButton.Position = TabVisualsContainer.Position + Vector2.new(244, 130)
                AutoRescanButtonInner.Position = AutoRescanButton.Position
                AutoRescanButtonLabel.Position = AutoRescanButton.Position + Vector2.new(25, 4)
                AutoRescanSlider.Position = TabVisualsContainer.Position + Vector2.new(352, 73)
                local percent = (Settings.autoRescanInterval - 1) / 29
                AutoRescanSliderKnob.Position = AutoRescanSlider.Position + Vector2.new((90 * percent) - 10, -5)
                AutoRescanValueText.Position = AutoRescanSlider.Position + Vector2.new(45, -12)
                KeybindForceRescan.Position = TabVisualsContainer.Position + Vector2.new(244, 103)
                KeybindForceRescanBorder.Position = KeybindForceRescan.Position
                KeybindForceRescanText.Position = KeybindForceRescan.Position + Vector2.new(34, 9.5)
                ForceRescanLabel.Position = TabVisualsContainer.Position + Vector2.new(324, 108)

                -- Misc Container
                MiscTABcontainer1.Position = newPos + Vector2.new(210.5, 64)
                AutoHideGUI.Position = MiscTABcontainer1.Position + Vector2.new(21, 19)
                AutoHideGUIInner.Position = AutoHideGUI.Position
                AutoHideGUILabel.Position = AutoHideGUI.Position + Vector2.new(25, 4)
                WatermarkButton.Position = MiscTABcontainer1.Position + Vector2.new(21, 50.5)
                WatermarkButtonInner.Position = WatermarkButton.Position
                WatermarkButtonLabel.Position = WatermarkButton.Position + Vector2.new(25, 4)
            end

            local f1Pressed = iskeypressed(0x70)
            if f1Pressed and not lastF1 then
                ToggleGUI()
            end
            lastF1 = f1Pressed
            lastMouse1 = mouse1
        end
    end
end)

print("=== PRESSURE SCRIPT LOADED ===")
